### PR TITLE
Check for rescript.json when searching for a project root

### PR DESCRIPTION
**Pull request by alex35mil**

### CODE REVIEW

**Review by mununki — APPROVED** [review]
Looking great! Thanks!

**Comment by mununki** [comment]
Anything left to do for this PR? or I'll merge it.

**Comment by alex35mil** [comment]
I didn't update changelog, otherwise, it should be good to go.

**Comment by alex35mil** [comment]
Updated CHANGELOG.

**Comment by mununki** [comment]
> Updated CHANGELOG.

Thanks! I'll release it to npm now.

**Comment by mununki** [comment]
> > Updated CHANGELOG.
> 
> Thanks! I'll release it to npm now.

Done: https://www.npmjs.com/package/@greenlabs/res-tailwindcss/v/0.1.14

**Pull request merged**
